version: '3.1'
services:
  web:
    image: fbieringer/odoo:15-arm64
#    platform: linux/amd64
    command: odoo --dev reload,qweb,werkzeug,xml -d sulaba --db-filter sulaba -init
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./odoo:/usr/lib/python3/dist-packages/odoo
  db:
    image: arm64v8/postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
